version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - misspell
    - noctx
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
    - gosec
    - copyloopvar
    - errorlint

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/NodeOps-app/createos-cli

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: exported
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: indent-error-flow
        disabled: false
  gosec:
    excludes:
      - G304

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
